name: Rick and Morty App CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    

    - name: Build Rick and Morty App
      run: xcodebuild -scheme "RickAndMortySwiftUI" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' build

    - name: Run Tests
      run: xcodebuild test -scheme "RickAndMortySwiftUI" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5'
